#!/bin/sh

# wrap-for-bin.sh: Template for git executable wrapper scripts
# to run test suite against sandbox, but with only bindir-installed
# executables in PATH.  The Makefile copies this into various
# files in bin-wrappers, substituting
# C:/Users/sondr/Documents/GitHub/git/o and git-receive-pack.exe.

GIT_EXEC_PATH='C:/Users/sondr/Documents/GitHub/git/o'
if test -n "$NO_SET_GIT_TEMPLATE_DIR"
then
	unset GIT_TEMPLATE_DIR
else
	GIT_TEMPLATE_DIR='C:/Users/sondr/Documents/GitHub/git/o/templates/blt'
	export GIT_TEMPLATE_DIR
fi
GITPERLLIB='C:/Users/sondr/Documents/GitHub/git/o/perl/build/lib'"${GITPERLLIB:+:$GITPERLLIB}"
GIT_TEXTDOMAINDIR='C:/Users/sondr/Documents/GitHub/git/o/po/build/locale'
PATH='C:/Users/sondr/Documents/GitHub/git/o/bin-wrappers:'"$PATH"

export GIT_EXEC_PATH GITPERLLIB PATH GIT_TEXTDOMAINDIR

case "$GIT_DEBUGGER" in
'')
	exec "${GIT_EXEC_PATH}/git-receive-pack.exe" "$@"
	;;
1)
	unset GIT_DEBUGGER
	exec gdb --args "${GIT_EXEC_PATH}/git-receive-pack.exe" "$@"
	;;
*)
	GIT_DEBUGGER_ARGS="$GIT_DEBUGGER"
	unset GIT_DEBUGGER
	exec ${GIT_DEBUGGER_ARGS} "${GIT_EXEC_PATH}/git-receive-pack.exe" "$@"
	;;
esac
